sudo: required
language: bash
services:
  - docker

# Deploy to production
deploy:
  - provider: script
    skip_cleanup: true
    script: ./docker-push.sh
    on:
      branch: master
      tags: true